preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  com.android.application:
    alias: android-application
    version: 8.7.3
  com.android.library:
    alias: android-library
    version-ref: com.android.application
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 2.1.0

libraries:
  com.highcapable.betterandroid:
    ui-component:
      version: 1.0.5
    ui-extension:
      version: 1.0.4
    system-extension:
      version: 1.0.1
    compose-extension:
      version: 1.0.2
  com.highcapable.flexiui:
    core-android:
      version: 0.1.0-alpha01
      # Flexi UI is in alpha stage for now.
      version-filter:
        use-internal: false
  androidx.compose:
    compose-bom:
      version: 2024.11.00
  androidx.compose.ui:
    ui:
      version: <no-spec>
    ui-graphics:
      version: <no-spec>
    ui-tooling:
      version: <no-spec>
    ui-tooling-preview:
      version: <no-spec>
  androidx.compose.foundation:
    foundation:
      version: <no-spec>
  androidx.navigation:
    navigation-compose:
      version: 2.8.4
  androidx.activity:
    activity:
      version: 1.9.3
    activity-compose:
      version: 1.9.3
  junit:
    junit:
      version: 4.13.2
  androidx.test.ext:
    junit:
      version: 1.2.1
  androidx.test.espresso:
    espresso-core:
      version: 3.6.1